### ISSUE TITLE
Travis CI for building NPM package.

### ISSUE THREAD

**Issue by mrstebo** [kmalakoff/node-nuget#3]
As I mentioned in #2, I think we should use TravisCI for publishing this NPM package.

Here is an example configuration:

```yaml
language: node_js
node_js:
- 0.8.0
before_deploy:
- npm run build
deploy:
  provider: npm
  email: <your_email>
  api_key:
    secure: <your_encrypted_api_key>
  on:
    tags: true
    repo: kmalakoff/node-nuget
```

I think that should work.
